spring:
  application:
    name: securepay

  config:
    import: optional:file:.env[.properties]

  jwt:
    secretKey: ${JWT_SECRET}
    accessTokenExpiration: ${ACCESS_TOKEN_EXPIRATION} # 900 15 minutes
    refreshTokenExpiration: ${REFRESH_TOKEN_EXPIRATION} # 604800 7 days

  profiles:
    active: dev

stripe:
  secretKey: ${STRIPE_SECRET_KEY}
  webhookSecretKey: ${STRIPE_WEBHOOK_SECRET_KEY}

fenanpay:
  apiBaseUrl: ${FENAN_PAY_API_BASE_URL}
  apiKey: ${FENAN_PAY_API_KEY}

  secretKey: ${FENAN_PAY_SECRET_KEY}
  webhookSecretKey: ${FENAN_PAY_WEBHOOK_SECRET_KEY}

allowedOrigins: ${ALLOWED_ORIGINS}

