spring:
  application:
    name: securepay
  datasource:
    url: jdbc:mysql://localhost:3306/securepay?createDatabaseIfNotExist=true
    username: root
    password: MyPassword!1234

  jpa:
    show-sql: true

  jwt:
    secreteKey: opensslE1De/s8IVe0DSwgYcJduqn1pCuDVXehGUkTQGUhvqCkdgYiF4tsXH9PQk4ihmJV+yKSfJirfF/00SsAXkuYqEg==
    accessTokenExpiration: 900 # 15 minutes
    refreshTokenExpiration: 604800 # 7 days

